"""create approvals executions and rollback_snapshots tables

Revision ID: fe717de5f9a0
Revises: 68dd206117f4
Create Date: 2026-04-10 12:23:22.802160
"""

from __future__ import annotations

import sqlalchemy as sa

from alembic import op

# Revision identifiers, used by Alembic.
revision = "fe717de5f9a0"
down_revision = "68dd206117f4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """
    Apply this migration.

    C4 uses this template so later revisions in C5+ have a clean, typed starting point.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "approvals",
        sa.Column(
            "id", sa.Uuid(), nullable=False, comment="Primary identifier for the approval record."
        ),
        sa.Column("run_id", sa.UUID(), nullable=False, comment="Foreign key to the parent run."),
        sa.Column(
            "plan_id", sa.UUID(), nullable=False, comment="Foreign key to the associated plan."
        ),
        sa.Column(
            "decision",
            sa.String(length=50),
            nullable=False,
            comment="Approval decision such as approved, rejected, or cancelled.",
        ),
        sa.Column(
            "decided_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="UTC time when the approval decision was recorded.",
        ),
        sa.Column(
            "reason",
            sa.Text(),
            nullable=True,
            comment="Optional user or system note explaining the approval decision.",
        ),
        sa.ForeignKeyConstraint(["plan_id"], ["plans.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_approvals_plan_id"), "approvals", ["plan_id"], unique=False)
    op.create_index(op.f("ix_approvals_run_id"), "approvals", ["run_id"], unique=False)
    op.create_table(
        "executions",
        sa.Column(
            "id", sa.Uuid(), nullable=False, comment="Primary identifier for the execution record."
        ),
        sa.Column("run_id", sa.UUID(), nullable=False, comment="Foreign key to the parent run."),
        sa.Column(
            "action_id",
            sa.UUID(),
            nullable=False,
            comment="Foreign key to the executed plan action.",
        ),
        sa.Column(
            "status",
            sa.String(length=50),
            nullable=False,
            comment="Execution status such as pending, succeeded, failed, or skipped.",
        ),
        sa.Column(
            "result_json",
            sa.JSON(),
            nullable=True,
            comment="Structured execution result payload for successful or partial outcomes.",
        ),
        sa.Column(
            "error_json",
            sa.JSON(),
            nullable=True,
            comment="Structured execution error payload for failures.",
        ),
        sa.Column(
            "executed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="UTC time when the execution result was recorded.",
        ),
        sa.ForeignKeyConstraint(["action_id"], ["plan_actions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_executions_action_id"), "executions", ["action_id"], unique=False)
    op.create_index(op.f("ix_executions_run_id"), "executions", ["run_id"], unique=False)
    op.create_table(
        "rollback_snapshots",
        sa.Column(
            "id",
            sa.Uuid(),
            nullable=False,
            comment="Primary identifier for the rollback snapshot record.",
        ),
        sa.Column("run_id", sa.UUID(), nullable=False, comment="Foreign key to the parent run."),
        sa.Column(
            "action_id",
            sa.UUID(),
            nullable=False,
            comment="Foreign key to the plan action this rollback snapshot belongs to.",
        ),
        sa.Column(
            "snapshot_type",
            sa.String(length=100),
            nullable=False,
            comment="Rollback snapshot type, such as file_backup or setting_previous_value.",
        ),
        sa.Column(
            "snapshot_json",
            sa.JSON(),
            nullable=False,
            comment="Structured rollback payload used to revert the action later.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="UTC time when the rollback snapshot was recorded.",
        ),
        sa.ForeignKeyConstraint(["action_id"], ["plan_actions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_rollback_snapshots_action_id"), "rollback_snapshots", ["action_id"], unique=False
    )
    op.create_index(
        op.f("ix_rollback_snapshots_run_id"), "rollback_snapshots", ["run_id"], unique=False
    )
    op.create_unique_constraint(
        "uq_plan_actions_plan_id_action_index", "plan_actions", ["plan_id", "action_index"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Revert this migration.

    Every migration should keep downgrade logic explicit, even early in the project.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_plan_actions_plan_id_action_index", "plan_actions", type_="unique")
    op.drop_index(op.f("ix_rollback_snapshots_run_id"), table_name="rollback_snapshots")
    op.drop_index(op.f("ix_rollback_snapshots_action_id"), table_name="rollback_snapshots")
    op.drop_table("rollback_snapshots")
    op.drop_index(op.f("ix_executions_run_id"), table_name="executions")
    op.drop_index(op.f("ix_executions_action_id"), table_name="executions")
    op.drop_table("executions")
    op.drop_index(op.f("ix_approvals_run_id"), table_name="approvals")
    op.drop_index(op.f("ix_approvals_plan_id"), table_name="approvals")
    op.drop_table("approvals")
    # ### end Alembic commands ###
