"""create runs plans and plan_actions tables

Revision ID: 68dd206117f4
Revises: 20260410_000001
Create Date: 2026-04-10 12:02:16.186630
"""

from __future__ import annotations

import sqlalchemy as sa

from alembic import op

# Revision identifiers, used by Alembic.
revision = "68dd206117f4"
down_revision = "20260410_000001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """
    Apply this migration.

    C4 uses this template so later revisions in C5+ have a clean, typed starting point.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "runs",
        sa.Column("id", sa.Uuid(), nullable=False, comment="Primary identifier for the run."),
        sa.Column(
            "user_id",
            sa.String(length=255),
            nullable=True,
            comment="Optional user identifier for future authenticated modes.",
        ),
        sa.Column(
            "request_text",
            sa.Text(),
            nullable=False,
            comment="The raw user request text submitted to the system.",
        ),
        sa.Column(
            "request_class",
            sa.String(length=50),
            nullable=True,
            comment="Request class such as explain, inspect, configure, repair, or guide.",
        ),
        sa.Column(
            "workspace_id",
            sa.String(length=255),
            nullable=True,
            comment="Optional workspace identifier if the backend later tracks stable workspaces.",
        ),
        sa.Column(
            "status",
            sa.String(length=50),
            nullable=False,
            comment="Current lifecycle status for the run.",
        ),
        sa.Column(
            "trace_id",
            sa.String(length=255),
            nullable=True,
            comment="Optional trace identifier for observability/debugging.",
        ),
        sa.Column(
            "metadata_json",
            sa.JSON(),
            nullable=True,
            comment="Optional structured request metadata captured alongside the run.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="UTC time when this row was created.",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="UTC time when this row was last updated.",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "plans",
        sa.Column("id", sa.Uuid(), nullable=False, comment="Primary identifier for the plan."),
        sa.Column("run_id", sa.UUID(), nullable=False, comment="Foreign key to the parent run."),
        sa.Column(
            "plan_json",
            sa.JSON(),
            nullable=False,
            comment="Full structured plan payload returned by the planner.",
        ),
        sa.Column(
            "risk_summary",
            sa.Text(),
            nullable=True,
            comment="Human-readable or summarized risk description for the plan.",
        ),
        sa.Column(
            "planner_version",
            sa.String(length=100),
            nullable=True,
            comment="Planner/provider version used when generating this plan.",
        ),
        sa.Column(
            "action_count",
            sa.Integer(),
            nullable=False,
            comment="Cached number of normalized plan actions linked to this plan.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="UTC time when this row was created.",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="UTC time when this row was last updated.",
        ),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_plans_run_id"), "plans", ["run_id"], unique=False)
    op.create_table(
        "plan_actions",
        sa.Column(
            "id", sa.Uuid(), nullable=False, comment="Primary identifier for the plan action row."
        ),
        sa.Column("plan_id", sa.UUID(), nullable=False, comment="Foreign key to the parent plan."),
        sa.Column(
            "action_index",
            sa.Integer(),
            nullable=False,
            comment="The zero-based order of this action inside the plan.",
        ),
        sa.Column(
            "action_type",
            sa.String(length=100),
            nullable=False,
            comment="Normalized action type, for example update_setting or patch_vscode_file.",
        ),
        sa.Column(
            "scope",
            sa.String(length=50),
            nullable=False,
            comment="Action scope such as user, workspace, or file-based scope.",
        ),
        sa.Column(
            "risk_level",
            sa.String(length=50),
            nullable=False,
            comment="Risk level for this action.",
        ),
        sa.Column(
            "requires_approval",
            sa.Boolean(),
            nullable=False,
            comment="Whether this action requires explicit user approval.",
        ),
        sa.Column(
            "target",
            sa.String(length=255),
            nullable=True,
            comment="Primary action target, such as a setting key or file path.",
        ),
        sa.Column(
            "parameters_json", sa.JSON(), nullable=True, comment="Structured action parameters."
        ),
        sa.Column(
            "preview_json",
            sa.JSON(),
            nullable=True,
            comment="Structured preview metadata for this action.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="UTC time when this row was created.",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="UTC time when this row was last updated.",
        ),
        sa.ForeignKeyConstraint(["plan_id"], ["plans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_plan_actions_plan_id"), "plan_actions", ["plan_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Revert this migration.

    Every migration should keep downgrade logic explicit, even early in the project.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_plan_actions_plan_id"), table_name="plan_actions")
    op.drop_table("plan_actions")
    op.drop_index(op.f("ix_plans_run_id"), table_name="plans")
    op.drop_table("plans")
    op.drop_table("runs")
    # ### end Alembic commands ###
